name: Upload Docker Image to GHCR

on:
  release:
    types: [published]

jobs:
  release-image:
    name: Release NeuroConv Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.MY_GITHUB_USERNAME }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true  # Push is a shorthand for --output=type=registry
          tags:
            - ghcr.io/CatalystNeuro/NeuroConv:latest
            - ghcr.io/CatalystNeuro/NeuroConv:0.3.1  # TODO, figure out how to auto-set this
          context: docker
          file: dockerfiles/neuroconv_developer_build_dockerfile
