name: Deploy tests

on:
  pull_request:

jobs:
  assess-file-changes:
    uses: catalystneuro/neuroconv/.github/workflows/assess-file-changes.yml@disable_tests_if_no_changes

  run-tests:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: catalystneuro/neuroconv/.github/workflows/testing.yml@disable_tests_if_no_changes
    secrets:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

  run-doctest:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.CONVERSION_GALLERY_CHANGED == 'true' && needs.assess-file-changes.outputs.SOURCE_CHANGED != 'true' }}
    uses: catalystneuro/neuroconv/.github/workflows/doctests.yml@disable_tests_if_no_changes
