name: Deploy tests

on:
  pull_request:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

  assess-file-changes:
    uses: catalystneuro/neuroconv/.github/workflows/assess-file-changes.yml@main

  run-tests:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: catalystneuro/neuroconv/.github/workflows/testing.yml@main
    secrets:
      DANDI_API_KEY: ${{ secrets.DANDI_API_KEY }}

  run-doctest:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.CONVERSION_GALLERY_CHANGED == 'true' && needs.assess-file-changes.outputs.SOURCE_CHANGED != 'true' }}
    uses: catalystneuro/neuroconv/.github/workflows/doctests.yml@main
