name: Deploy tests

on:
  pull_request:

jobs:
  assess-file-changes:
    uses: catalystneuro/neuroconv/.github/workflows/assess-file-changes.yml@disable_tests_if_no_changes

  run-tests:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    uses: catalystneuro/neuroconv/.github/workflows/testing.yml@disable_tests_if_no_changes
