name: Update testing data
on: push  # initial setup
# on:
#   schedule:
#     - cron:  '0 0 * * *'
jobs:
  run:
    name: Update testing data
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    steps:
    - uses: s-weigand/setup-conda@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    # - uses: actions/cache@v2
    #   id: cache-venv
    #   with:
    #     path: ~/datalad_env
    #     key: ${{ runner.os }}-venv-test-datalad
    #     restore-keys: |
    #       ${{ runner.os }}-venv-test
    - uses: syphar/restore-virtualenv@v1
      id: cache-datalad-env
    - name: Get cached environment, or install
      run: |
        conda install -c conda-forge datalad==0.14.5
        git config --global user.email "CI@example.com"
        git config --global user.name "CI Almighty"
      if: steps.cache-datalad-env.outputs.cache-hit != "true"
    # - name: Install datalad
    #   run: |
    #     python -m venv ~/datalad_env
    #     source ~/datalad_env/bin/activate
        # conda install -c conda-forge datalad==0.14.5
        # git config --global user.email "CI@example.com"
        # git config --global user.name "CI Almighty"
    - name: Get ephy_testing_data current head hash
      id: vars
      run: |
        echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
    - uses: actions/cache@v2
      id: cache-datasets
      with:
        path: ~/ephy_testing_data
        key: ${{ runner.os }}-dataset-test1-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
        restore-keys: |
          ${{ runner.os }}-dataset-test1
    - name: Update dataset
      run: |
        # python -m venv ~/datalad_env
        # source ~/datalad_env/bin/activate
        datalad install -r https://gin.g-node.org/NeuralEnsemble/ephy_testing_data
        cd ephy_testing_data
        datalad get spikegadgets
        datalad get neuroscope
        echo $(pwd)
        echo $(ls)
        echo $(~/ephy_testing_data)
        cd ~/ephy_testing_data
        echo $(ls)
